apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gwjjpf1mt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gwjjpf1mt-python 
  name: gwjjpf1mt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gwjjpf1mt-python 
